version: '3'

services:
  eureka-server:
    image: riadhyahyaoui/riadhapps:eureka1
    container_name: eureka-server
    ports:
      - "8761:8761"
  gateway:
    image: gateriadh
    container_name: gateway
    ports:
      - "8888:8888"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
  relationship:
    image: rel
    container_name: relationship
    ports:
      - "8080:8080"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - gateway
  assurance:
    image: assurance
    container_name: assurance
    ports:
      - "8081:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - gateway
  angular:
    image: angular2
    container_name: angular
    ports:
      - "4200:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"